spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/your-pulse?useSSL=false
        username: postgres
        password: postgresql
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
server:
    port: 8090